### ISSUE TITLE
Could not find a declaration file for module 'react-image-hotspots'

### ISSUE THREAD

**Issue by AnderSco01** [filipecorrea/react-image-hotspots#39]
Hi, I cannot seem to download this package from npm, I just get the following when trying to import it after downloading:

-----------------------
'ImageHotspots' is declared but its value is never read.ts

Could not find a declaration file for module 'react-image-hotspots'. 'C:/Users/scott.anderson/source/repos/Onpoint Site Engineering - Report360 Platform V1.0/report360/node_modules/react-image-hotspots/dist/ImageHotspots.js' implicitly has an 'any' type.

Try `npm i --save-dev @type/react-image-hotspots` if it exists or add a new declaration (.d.ts) file containing `declare module `react-image-hotspots';`
-----------------------

I tried the --save-dev install but to no avail, any help would be great, thank you.

**Comment by PenguinOfWar** [comment]
You will need to add the following to your `.d.ts` file:

`declare module 'react-image-hotspots';`

For example, if you use `create-react-app` your definition file will be `src/react-app-env.d.ts`.

**Comment by filipecorrea** [comment]
I'm very sorry! This project was a bit abandoned, but I'm planning to update it from now on.

This issue will also be probably fixed by https://github.com/filipecorrea/react-image-hotspots/issues/62.

It would be awesome if you could help me by also contributing to the source code if you can. See you around!
